### PR TITLE
add displayDelete prop to candidate list

### LINKED ISSUE #199: Create a CandidateList container component
## **User story** 
**Who:** As a developer
**What:** I want to create a CandidateList container that will contain a list of the candidates and send PUT requests when the ordering changes.
**Why:** So that BoardPage will be able to send the last state of rank of the candidates.
## **Acceptance criteria**

Issue #195 and #197 should be merged to let this component work.

### PR DESCRIPTION
**Pull request by Rasim-Deniz**
# Description

Added displayDelete prop to candidate list

### CODE REVIEW

**Comment by senner007** [comment]
@Rasim-Deniz 
What does this pr do?

**Comment by Rasim-Deniz** [comment]
> @Rasim-Deniz 
> What does this pr do?

This is for not displaying deleteIcon in MembersBoardPage.

**Comment by senner007** [comment]
> > @Rasim-Deniz
> > What does this pr do?
> 
> This is for not displaying deleteIcon in MembersBoardPage.

Ok.
There is still some changes needed here. 
Candidate lists must not be draggable post deadline. In another pr.

**Comment by Rasim-Deniz** [comment]
> > > @Rasim-Deniz
> > > What does this pr do?
> > 
> > 
> > This is for not displaying deleteIcon in MembersBoardPage.
> 
> Ok.
> There is still some changes needed here.
> Candidate lists must not be draggable post deadline. In another pr.

They are not draggable at post deadline right now.

**Comment by senner007** [comment]
> > > > @Rasim-Deniz
> They are not draggable at post deadline right now.

Alright then its just the sortable item component that needs to be removed

**Pull request merged**
