### PR TITLE
Production deployment 

### LINKED ISSUE #154: Deployment: Ensure App Deployment - develop branch for Milestone 1
## User story

**Who: As a** developer
**What: I want to be** able to see the development version online on https://staging-simply-name-it.herokuapp.com/
**Why: so that I can** test it in **DEVELOPMENT** before is goes to Production

## Acceptance criteria

Make sure that every **PR builds** on Develop and that the **Develop Heroku DB** is up to date and with the correct credentials, and both Migrations and Seeding are updated in this environment. 

image

## Implementation details

Check the env variables on https://dashboard.heroku.com/apps/staging-simply-name-it/settings and **DO NOT SHARE or COMMIT any information about Users or Passwords.**

### PR DESCRIPTION
**Pull request by islam-fawzy25**
# Description

we need to update master for production deployment 
Fixes #154

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by senner007 — CHANGES_REQUESTED** [review]
Pr. has unrelated changes
Nomally you don't add seeds for production, since that data is real and generated by real users.

**Comment by islam-fawzy25** [comment]
> Pr. has unrelated changes
> Nomally you don't add seeds for production, since that data is real and generated by real users.

ok 
i will revert that commit

**Comment by senner007** [comment]
@islam-fawzy25 
I believe the entire develop branch goes into master at some point

**Comment by islam-fawzy25** [comment]
> @islam-fawzy25
> I believe the entire develop branch goes into master at some point

yes , i saw that there but why Daniel asked me to make a PR !?

**Comment by dpfernandes** [comment]
> > @islam-fawzy25
> > I believe the entire develop branch goes into master at some point
> 
> yes , i saw that there but why Daniel asked me to make a PR !?

 
@senner007 I understand your points but I want us to demo from production and leave staging alone for people to play around. So let's please treat production like it's a copy of staging and not a real world production.

**Comment by senner007** [comment]
I'm closing this as prs are concerned with code that is ready to be merged. It can be reopened when the time comes

**Pull request closed without merging**
