### PR TITLE
Calculate results for boards that have reached the deadline 

### LINKED ISSUE #153: Backend: Calculate results for boards that have reached their deadline
## User story

**Who:** **As a** developer
**What:** **I want to** calculate the election results on the a board's deadline
**Why:** **so that Users** can see the result on time 

## Acceptance criteria

Results get calculated and inserted into the results table after the deadline.

## Hints

**The results endpoint**

   1. An endpoint must be created that is called from the results page. Here its first checks in the database if the deadline has been reached. If the deadline has not been reached it should return an error and signal to the frontend that the results are not visible yet.
   2. If the deadline has been reached it should call the endpoint or use the library below to calculate the results and insert into the results table. It should then return the results to be viewed on the frontend.
   
**Calculating the results** 

  1. Solution 1 :  
  The function should call https://api-nameit.budding.dev/docs#/default/compute_ranking_election_post (some changes to that endpoint might be coming) with all the ballots to create the result and then insert it into the results table.
    **EDIT**
 2. Solution alternative:
  A slightly faster way of computing the results is to use a node library instead:
  https://github.com/lzear/votes
   ` npm install votes`

### PR DESCRIPTION
**Pull request by Bhuvaneshwari29**
# Description

Calculate results for boards that have reached their deadline

Fixes #153 

# How to test?

npm run dev

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by Bhuvaneshwari29** [comment]
Hi @senner007 @Midnighter 
1. Boards with no result
2. Implement node schedule deadline inside the query.
3. Function
3a. Retrieve all the ballots for the specific board
3b. Call the result endpoint
3c. Store the result in the database.

Only task number 1 is completed. We are working on other things. This PR was made so that others can also work from here.
Thanks !!

**Comment by senner007** [comment]
@Bhuvaneshwari29 
What is the status here?

**Comment by Bhuvaneshwari29** [comment]
> @Bhuvaneshwari29
> What is the status here?

@senner007 Hi Niels, I think there are lot of things to do in this issue. Today i took help from study group to understand the approach.                   

  if (deadline for voting is over <-- KNEX (select boards table)) {
  if (the results have been calculated <-- KNEX (select results table)) {
    get results from the DB <-- KNEX (select results table)
    response: results <-- Express (res.send())
  }
  else {
    calculate the results:
      - get all the data from the DB <-- KNEX (select ballots table)
      - do the calculation <-- Node (`votes` library: https://www.npmjs.com/package/votes)
    write the results to the DB <-- KNEX (insert into results table)
    response: results <-- Express (res.send())
  }
}
else {
  response: Error: the board is still open,
    it hasn't reached the deadline <-- Express (res.send())
}

If there are changes to this approach, let me know.

**Comment by Rasim-Deniz** [comment]
@senner007 Hi Niels, could you please have a look at our [last commit](https://github.com/HackYourFuture-CPH/simply-name.it/commit/04c563a66951504781cc0e19f14039b2486180db) to see if we are in the right way?

**Comment by senner007** [comment]
> > @Bhuvaneshwari29
> > What is the status here?
> 
> @senner007 Hi Niels, I think there are lot of things to do in this issue. Today i took help from study group to understand the approach.
> 
> if (deadline for voting is over <-- KNEX (select boards table)) {
> if (the results have been calculated <-- KNEX (select results table)) {
> get results from the DB <-- KNEX (select results table)
> response: results <-- Express (res.send())
> }
> else {
> calculate the results:
> - get all the data from the DB <-- KNEX (select ballots table)
> - do the calculation <-- Node (`votes` library: https://www.npmjs.com/package/votes)
> write the results to the DB <-- KNEX (insert into results table)
> response: results <-- Express (res.send())
> }
> }
> else {
> response: Error: the board is still open,
> it hasn't reached the deadline <-- Express (res.send())
> }
> 
> If there are changes to this approach, let me know.

This seems correct 👍

**Comment by senner007** [comment]
> @senner007 Hi Niels, could you please have a look at our [last commit](https://github.com/HackYourFuture-CPH/simply-name.it/commit/04c563a66951504781cc0e19f14039b2486180db) to see if we are in the right way?

Also seems correct. Test thoroughly in swagger. Just need to insert the calculation

**Comment by Rasim-Deniz** [comment]
> > @senner007 Hi Niels, could you please have a look at our [last commit](https://github.com/HackYourFuture-CPH/simply-name.it/commit/04c563a66951504781cc0e19f14039b2486180db) to see if we are in the right way?
> 
> Also seems correct. Test thoroughly in swagger. Just need to insert the calculation

How can we insert the calculation? I'm not sure how we can use this https://api-nameit.budding.dev/docs#/default/compute_ranking_election_post endpoint.

**Comment by senner007** [comment]
> > > @senner007 Hi Niels, could you please have a look at our [last commit](https://github.com/HackYourFuture-CPH/simply-name.it/commit/04c563a66951504781cc0e19f14039b2486180db) to see if we are in the right way?
> > 
> > 
> > Also seems correct. Test thoroughly in swagger. Just need to insert the calculation
> 
> How can we insert the calculation? I'm not sure how we can use this https://api-nameit.budding.dev/docs#/default/compute_ranking_election_post endpoint.

I think you should use the library instead. If you go to the github it has an example

**Comment by Rasim-Deniz** [comment]
> > > > @senner007 Hi Niels, could you please have a look at our [last commit](https://github.com/HackYourFuture-CPH/simply-name.it/commit/04c563a66951504781cc0e19f14039b2486180db) to see if we are in the right way?
> > > 
> > > 
> > > Also seems correct. Test thoroughly in swagger. Just need to insert the calculation
> > 
> > 
> > How can we insert the calculation? I'm not sure how we can use this https://api-nameit.budding.dev/docs#/default/compute_ranking_election_post endpoint.
> 
> I think you should use the library instead. If you go to the github it has an example

Is that library installed? I guess you mean this library https://github.com/lzear/votes right?

**Comment by senner007** [comment]
> > > > > @senner007 Hi Niels, could you please have a look at our [last commit](https://github.com/HackYourFuture-CPH/simply-name.it/commit/04c563a66951504781cc0e19f14039b2486180db) to see if we are in the right way?
> > > > 
> > > > 
> > > > Also seems correct. Test thoroughly in swagger. Just need to insert the calculation
> > > 
> > > 
> > > How can we insert the calculation? I'm not sure how we can use this https://api-nameit.budding.dev/docs#/default/compute_ranking_election_post endpoint.
> > 
> > 
> > I think you should use the library instead. If you go to the github it has an example
> 
> Is that library installed? I guess you mean this library https://github.com/lzear/votes right?

No, you can see that if you look in package.json. Create a pr to install the library

**Pull request closed without merging**
