### PR TITLE
Install node-schedule package

### PR DESCRIPTION
**Pull request by senner007**
# Description

Install node-schedule package

# How to test?

Should be able to require package and schedule a function to execute in the future

```
const schedule = require('node-schedule');
const moment = require('moment-timezone');

const date = moment().add(30, "seconds").toDate()

const job = schedule.scheduleJob(date, function(){
  console.log('Called!.');
});

```

# Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by Midnighter — COMMENTED** [review]
Weird, I thought I had added this already. There seem to be a lot of changes in the package-lock.json, though. Are we silently updating the project accidentally?

**Comment by senner007** [comment]
> Weird, I thought I had added this already. There seem to be a lot of changes in the package-lock.json, though. Are we silently updating the project accidentally?

Oh it was already in? What pr?

**Comment by senner007** [comment]
> > Weird, I thought I had added this already. There seem to be a lot of changes in the package-lock.json, though. Are we silently updating the project accidentally?
> 
> Oh it was already in? What pr?

No I can see its not in develop. 
I used npm v6 and the change make sense. It adds some dependencies to cron-job and date handling

**Review by Midnighter — APPROVED** [review]

**Review by Bhuvaneshwari29 — COMMENTED** [review]
It works fine !!

**Review by Bhuvaneshwari29 — APPROVED** [review]
Hi Niels @senner007 It works fine!!

**Pull request merged**
