### PR TITLE
Dropzone component added.

### LINKED ISSUE #83: Storybook: Dropzone component to upload image files for the Board Banner
### **User story**
**Who:** As a developer
**What: we want to have** Dropzone component .
**Why: so that we can** enable the user to dropzone and upload image files for the Banner

### **Acceptance criteria**
Create a storybook component for the Dropzone component like shown below and make sure that when you hover over the component it shows the border like we can see on the third image

Screenshot 2021-07-30 at 18 31 57

Screenshot 2021-07-30 at 18 43 46
Screenshot 2021-07-30 at 18 43 52

### **Implementation details**
Use this example to implement the component 
https://codesandbox.io/s/bcobw

Create a separate PR where you add npm react-dropzone (npm install --save react-dropzone - https://react-dropzone.js.org/)

### PR DESCRIPTION
**Pull request by DarinkaGM**
# Description

Dropzone component added. In progress. Problem rendering it on storybook

Fixes #83

# How to test?

Npm run storybook

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by DarinkaGM** [comment]
Screen Shot 2021-08-17 at 22 11 03
The component appears when starting storybook but it's not on the list of components and it's lost when refreshing the page.

**Comment by senner007** [comment]
@DarinkaGM 
Lets us know if you need help with this

**Comment by DarinkaGM** [comment]
> @DarinkaGM
> Lets us know if you need help with this

Hi Niels, yes I do. I'm not sure how to approach it when there's an existing board and so the background of the DropzoneJS will be the current photo. 
Screen Shot 2021-08-21 at 14 33 04

**Comment by senner007** [comment]
> > @DarinkaGM
> > Lets us know if you need help with this
> 
> Hi Niels, yes I do. I'm not sure how to approach it when there's an existing board and so the background of the DropzoneJS will be the current photo.
> Screen Shot 2021-08-21 at 14 33 04

Ill have a look tomorrow

**Comment by DarinkaGM** [comment]
> Ill have a look tomorrow
>>Thank you @senner007  :)

**Comment by senner007** [comment]
> > Ill have a look tomorrow
> > > Thank you @senner007  :)

Hi.
As far as I can see, the visual component looks fine. It also takes an image and previews it.
What is needed here is a container component to retrieve the current board image and set it as the preview and to upload a new image

**Review by senner007 — APPROVED** [review]
✔

**Review by senner007 — APPROVED** [review]
✔

**Pull request merged**
