### PR TITLE
userIsOwner function fix in users.controller

### LINKED ISSUE #243: Backend: fix userIsOwner function in users.controller
userIsOwner function in users.controller should only check if the userId is the creatorId in 'boards' of the respective board id.

### PR DESCRIPTION
**Pull request by shpomp**
# Description

userIsOwner function fix in users.controller was not designed right. Simplified the query and fixed it. 

Fixes #243 

# How to test?

Try adding a member to the board

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by shpomp** [comment]
@senner007  I realize now there is no way to add the owner of the board now, as a member with role 'owner'. 

Should it be a separate endpoint, or just to pass the role as a parameter here? : 

```javascript
const addMember = async (userId, boardId, memberId) => {
  if (
    !Number.isInteger(Number(userId)) ||
    !Number.isInteger(Number(boardId)) ||
    !Number.isInteger(Number(memberId))
  ) {
    throw new InvalidIdError('Id should be an integer');
  }
  await userIsOwner(userId, boardId);

  const addNewMember = await knex('members').insert({
    boardId,
    userId: memberId,
    role: 'basic',
  });
  return addNewMember;
};
```
(from members.controller)

**Review by senner007 — APPROVED** [review]
✔

**Comment by senner007** [comment]
>     role: 'basic',
>   });
>   return addNewMember;
> };
> ```
> 
> (from members.controller)

Yah, you just want to change the role: 'owner' right?

**Comment by senner007** [comment]
I'm thinking it makes sense to add the owner as a owner member when the board gets created, right?

**Review by dinythomas89 — APPROVED** [review]
Its working fine

**Comment by senner007** [comment]
@Midnighter 
What do you think?

**Comment by senner007** [comment]
> Its working fine

Good :) I think you can easily finish your pr before this is merged

**Comment by shpomp** [comment]
> > ```
> > role: 'basic',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > });
> > return addNewMember;
> > };
> > ```
> > 
> > (from members.controller)
> > ```
> 
> Yah, you just want to change the role: 'owner' right?

yes. We just have no way of adding the owner with role 'owner' as a member to the member table now. Do we need it? 
If yes, there can be many ways to implement it. Which is the best? 
Passing the role as param would be the least changes 🙈

**Comment by senner007** [comment]
> > > ```
> > > role: 'basic',
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > });
> > > return addNewMember;
> > > };
> > > ```
> > > 
> > > (from members.controller)
> > > ```
> > 
> > 
> > Yah, you just want to change the role: 'owner' right?
> 
> yes. We just have no way of adding the owner with role 'owner' as a member to the member table now. Do we need it?
> If yes, there can be many ways to implement it. Which is the best?
> Passing the role as param would be the least changes 🙈

Ok then create a function with a parameter. When called here the parameter will be 'basic'. 
But also execute the function with the 'owner' parameter when the board is created

**Comment by shpomp** [comment]
> I'm thinking it makes sense to add the owner as a owner member when the board gets created, right?

Diny suggested a very short and smart solution too: 
```javascript
if(userId===memberId){
    const addNewMember = await knex('members').insert({
      boardId,
      userId: memberId,
      role: 'owner',
    });
    return addNewMember;
  }
  else{
    const addNewMember = await knex('members').insert({
    boardId,
    userId: memberId,
    role: 'basic',
  });
  return addNewMember;
}
```

**Comment by shpomp** [comment]
> > > > ```
> > > > role: 'basic',
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > });
> > > > return addNewMember;
> > > > };
> > > > ```
> > > > 
> > > > (from members.controller)
> > > > ```
> > > 
> > > 
> > > Yah, you just want to change the role: 'owner' right?
> > 
> > 
> > yes. We just have no way of adding the owner with role 'owner' as a member to the member table now. Do we need it?
> > If yes, there can be many ways to implement it. Which is the best?
> > Passing the role as param would be the least changes 🙈
> 
> Ok then create a function with a parameter. When called here the parameter will be 'basic'.
> But also execute the function with the 'owner' parameter when the board is created

Diny suggested a very short and smart solution too: 
```javascript
if(userId===memberId){
    const addNewMember = await knex('members').insert({
      boardId,
      userId: memberId,
      role: 'owner',
    });
    return addNewMember;
  }
  else{
    const addNewMember = await knex('members').insert({
    boardId,
    userId: memberId,
    role: 'basic',
  });
  return addNewMember;
}
```

What you think about just that?

**Comment by senner007** [comment]
> What you think about just that?

Fine by me if you don't mind adding the owner as member in the frontend also

**Comment by senner007** [comment]
> > What you think about just that?
> 
> Fine by me if you don't mind adding the owner as member in the frontend also

...and I would still prefer a function since you now have duplicated code

**Comment by shpomp** [comment]
> > > What you think about just that?
> > 
> > 
> > Fine by me if you don't mind adding the owner as member in the frontend also
> 
> ...and I would still prefer a function since you now have duplicated code

ok! 
Just to make sure I don't misunderstand - by 'create a function', do you mean just to introduce the role parameter to addMember, right? 
I would do simply like this:
```javascript
const addMember = async (userId, boardId, memberId, role) => {
  if (
    !Number.isInteger(Number(userId)) ||
    !Number.isInteger(Number(boardId)) ||
    !Number.isInteger(Number(memberId))
  ) {
    throw new InvalidIdError('Id should be an integer');
  }
  if (role !== 'basic' || role !== 'owner') {
    throw new IncorrectEntryError(`Role should be either 'basic' or 'owner'`);
  }
  await userIsOwner(userId, boardId);

  const addNewMember = await knex('members').insert({
    boardId,
    userId: memberId,
    role: role,
  });
  return addNewMember;
};
```

**Comment by senner007** [comment]
> > > > What you think about just that?
> > > 
> > > 
> > > Fine by me if you don't mind adding the owner as member in the frontend also
> > 
> > 
> > ...and I would still prefer a function since you now have duplicated code
> 
> ok!
> Just to make sure I don't misunderstand - by 'create a function', do you mean just to introduce the role parameter to addMembr, right?
> I would do simply like this:
> 
> ```js
> const addMember = async (userId, boardId, memberId, role) => {
>   if (
>     !Number.isInteger(Number(userId)) ||
>     !Number.isInteger(Number(boardId)) ||
>     !Number.isInteger(Number(memberId))
>   ) {
>     throw new InvalidIdError('Id should be an integer');
>   }
>   if (role !== 'basic' || role !== 'owner') {
>     throw new IncorrectEntryError(`Role should be either 'basic' or 'owner'`);
>   }
>   await userIsOwner(userId, boardId);
> 
>   const addNewMember = await knex('members').insert({
>     boardId,
>     userId: memberId,
>     role: role,
>   });
>   return addNewMember;
> };
> ```

That's also an option. Now the frontend has to know about the role parameter also. It might come in handy if more roles are added later

**Comment by senner007** [comment]
> > I would do simply like this:
> > ```js
> > const addMember = async (userId, boardId, memberId, role) => {
> >   if (
> >     !Number.isInteger(Number(userId)) ||
> >     !Number.isInteger(Number(boardId)) ||
> >     !Number.isInteger(Number(memberId))
> >   ) {
> >     throw new InvalidIdError('Id should be an integer');
> >   }
> >   if (role !== 'basic' || role !== 'owner') {
> >     throw new IncorrectEntryError(`Role should be either 'basic' or 'owner'`);
> >   }
> >   await userIsOwner(userId, boardId);
> > 
> >   const addNewMember = await knex('members').insert({
> >     boardId,
> >     userId: memberId,
> >     role: role,
> >   });
> >   return addNewMember;
> > };
> > ```

@shpomp 
Please create an issue for this

**Comment by shpomp** [comment]
> > > I would do simply like this:
> > > ```js
> > > const addMember = async (userId, boardId, memberId, role) => {
> > >   if (
> > >     !Number.isInteger(Number(userId)) ||
> > >     !Number.isInteger(Number(boardId)) ||
> > >     !Number.isInteger(Number(memberId))
> > >   ) {
> > >     throw new InvalidIdError('Id should be an integer');
> > >   }
> > >   if (role !== 'basic' || role !== 'owner') {
> > >     throw new IncorrectEntryError(`Role should be either 'basic' or 'owner'`);
> > >   }
> > >   await userIsOwner(userId, boardId);
> > > 
> > >   const addNewMember = await knex('members').insert({
> > >     boardId,
> > >     userId: memberId,
> > >     role: role,
> > >   });
> > >   return addNewMember;
> > > };
> > > ```
> 
> @shpomp
> Please create an issue for this

will do! I am working now 🧑‍🏭 , but will make it as soon as I get a moment

**Pull request merged**
